config/routes.rb
Rails.application.routes.draw do
  mount Lines::Engine => "/blog"
  root to: "lines/articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def trigger_build
    return 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def test_trigger
    puts "test_trigger"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/lines/application.html.erb
<!doctype html>
<html class="no-js">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="UTF-8" />
  <meta name="author" content="<%= CONFIG[:meta_author] %>" />
  <meta name="revisit-after" content="3 days" />
  <meta name="robots" content="index,follow" />
  <%= display_meta_tags site: CONFIG[:title_short] %>
  <meta name="geo.position" CONTENT="<%= CONFIG[:geo_position] %>">
  <meta name="geo.placename" CONTENT="<%= CONFIG[:geo_address] %>">
  <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1" />
  <%= favicon_link_tag %>
  <%= yield :head %>
  <%= auto_discovery_link_tag(:atom, articles_url(format: "atom"), {title: CONFIG[:feed_title]}) %>
  <%= stylesheet_link_tag    "lines/application", media: "all" %>
  <%= javascript_include_tag "lines/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_lines_user %>
  <%= render_navbar do %>
    <%= link_to t('lines.buttons.new_article').html_safe, new_admin_article_path, class: "btn btn-new-article highlight" %>  
    <%= link_to t('lines.buttons.dashboard').html_safe, admin_articles_path, class: "btn btn-view-blog" %>
  <% end %>
  <div class="spacer"></div>
<% end %>

<%= render 'layouts/lines/markdown_cheatsheet' %>

<header>
  <div id="logo">
    <a href="/">
      <% if CONFIG[:logo].empty? %>
        <%= CONFIG[:blog_name] %>
      <% else %>
        <img src="<%= CONFIG[:logo] %>" alt="<%= CONFIG[:blog_name] %>" />
      <% end %>
    </a>
  </div>
  <div id="lines">
    <%= CONFIG[:short_description].html_safe %>
  </div>
</header>

<div class="container">
  <%= render 'lines/shared/flash' %>
  <%= yield %>
</div>

<%= render 'lines/shared/footer' %>

</body>
</html>

app/views/layouts/lines/preview.html.erb
<!doctype html>
<html class="no-js">
<head>
  <meta charset="UTF-8" />
  <%= display_meta_tags site: CONFIG[:title_short] %>
  <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1" />
  <%= favicon_link_tag %>
  <%= yield :head %>
  <%= stylesheet_link_tag    "lines/application", media: "all" %>
  <%= javascript_include_tag "lines/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield :navbar %>

<%= render 'layouts/lines/markdown_cheatsheet' %>

<header>
  <div id="logo">
    <a href="/">
      <% if CONFIG[:logo].empty? %>
        <%= CONFIG[:blog_name] %>
      <% else %>
        <img src="<%= CONFIG[:logo] %>" alt="<%= CONFIG[:blog_name] %>" />
      <% end %>
    </a>
  </div>
  <div id="lines">
    <%= CONFIG[:short_description].html_safe %>
  </div>
</header>

<div class="container">
  <%= render 'lines/shared/flash' %>
  <%= yield %>
</div>

<%= render 'lines/shared/footer' %>

</body>
</html>

app/views/lines/articles/_article.html.erb
<div class="article first">

<% cache article do %>

  <% unless article.image_url.blank? %>
    <div class="hero_image">
      <%= link_to article_path(article) do %>
        <img src="<%= article.image_url %>" alt="<%= article.title %>" />
      <% end %>
    </div>
  <% end %>

  <div class="article_header">
    <h1><%= link_to article.title, article_path(article) %></h1>
    <h2><%= article.sub_title %></h2>
    <div class="author_name"><span>by</span> <%= display_article_authors(article) %></div>
  </div>

  <div class="article_teaser">
    <%= render_teaser(article, article_counter) %>
  </div>

  <div class="article_content">
    <%= markdown article.content %>
    <% if article.document? %>
    <div class="article_document">
      <%= link_to "Download #{article.document.file.filename}", article.document_url %>
    </div>
    <% end %>
  </div>

  <% unless article.gplus_url.blank? %>
    <div class="article_googleplus">
      <a href="<%= article.gplus_url %>">Discuss this article at Google+</a>
    </div>
  <% end %>
  
  <hr>

  <div class="article_footer">
    Written on <span class="published_at"><%= article.published_at.to_date %></span> by <%= display_article_authors(article, true) %>
  </div>
  
<% end %>
</div>

app/views/lines/articles/_article_collection.html.erb
<%= render partial: 'article_small', locals: { article_small: article_collection, article_class: 'small', article_counter: article_collection_counter } %>

<% if (article_collection_counter % 2) != 0 %>
  <div class="breaker" style="clear:both;height:1px;line-height:1px">&nbsp;</div>
<% end %>

app/views/lines/articles/_article_small.html.erb
<div class="article <%= article_class %>">
<% cache "#{article_small}_small" do %>
  <% unless article_small.image_url.blank? %>
    <div class="hero_image">
      <%= link_to article_path(article_small) do %>
        <img src="<%= article_small.image_url %>" alt="<%= article_small.title %>" />
      <% end %>
    </div>
  <% end %>

  <div class="article_header">
    <h1><%= link_to article_small.title, article_path(article_small) %></h1>
    <h2><%= article_small.sub_title %></h2>
    <div class="author_name"><span>by</span> <%= display_article_authors(article_small) %></div>
  </div>

  <div class="article_teaser">
    <%= render_teaser(article_small).html_safe %>
    <div class="more-link">
      <%= link_to "Read full article", article_path(article_small) %>
    </div>
  </div>
<% end %>
</div>

app/views/lines/articles/index.html.erb
<div class="rss">
    <%= link_to image_tag("ic_rss.png"), articles_url(format: "atom") %>
</div>

<div id="articles">
  <%= render partial: 'article_small', locals: { article_small: @first_article, article_class: 'first', article_counter: -1 } unless @first_article.nil? %>
  <%= render partial: 'article_collection', collection: @articles %>
</div>

<% if @articles.total_pages > 1 %>
<hr>
<div id="pagination">
  <%= paginate @articles, outer_window: 1, window: 2, theme: 'lines' %>
</div>
<% end %>

app/views/lines/articles/show.html.erb
<%= render @article, article_counter: -1 %>

<div id="articles">
  <%= render partial: 'article_collection', collection: @related_articles %>
</div>

app/views/lines/password_resets/edit.html.erb
<%= render_navbar {} %>
<div class="login">
  <h2>Set new password password</h2>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> occured:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      <a href="#" class="close">x</a>
    </div>
  <% end %>
      
  <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>

    <%= hidden_field_tag :email, @user.email %>

    <div class="input-field">
      <%= f.password_field :password, placeholder: 'Enter a new password' %>
    </div>
    
    <div class="input-field">
      <%= f.password_field :password_confirmation, placeholder: 'Confirm your passwword' %>    
    </div>

    <br style="clear: both;" />
    <div class="submit">
      <%= submit_tag "Set new password" %>
      <a href="/">or go back to your blog.</a>
    </div>
  <% end %>
  
</div>

app/views/lines/password_resets/new.html.erb
<%= render_navbar {} %>
<div class="login">
  <h2>Reset password</h2>
  
  <%= form_for(:password_reset, url: password_resets_path) do |f| %>
    <div class="input-field">
      <%= f.email_field :email, placeholder: 'E-Mail' %>
    </div>
    <br style="clear: both;" />
    <div class="submit">
      <%= submit_tag "Send password reset link" %> or <a href="/">go back to your blog.</a>
    </div>
  <% end %>
</div>

app/views/lines/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/lines/shared/_footer.html.erb
<footer id="footer">
  <div class="container">
    <p>FXCE Developer By <a target="_blank" href="https://t.me/huancapital">
      Huan Capital
    </a></p>
  </div>
</footer>

app/views/lines/shared/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <nav class="navbar-inner">
    <div class="container">
      <a class="brand" href="/admin"><%= CONFIG[:title_short] %></a>

      <ul class="user-info">
        <% if current_lines_user %>
          <li><%= current_lines_user.email %></li>
          <li><a href="<%= logout_path %>"><%= t('lines.buttons.logout').html_safe %></a></li>
        <% end %>
      </ul>
      <br class="clear" />
    </div>
  </nav>
</div>


    